# Generated by Django 4.2.9 on 2024-02-02 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='username',
            field=models.CharField(default='imadege1990@gmail.com', max_length=255, verbose_name='username'),
            preserve_default=False,
        ),
    ]
